---
version: 3.8.5
name: TrungNq3388 • Developer
description: Transform your plain text into static websites and blogs
url: https://github.com/chameron
repository: https://github.com/chameron/trungnq3388.github.io
timezone: America/Los_Angeles
logo: "/img/logo-2x.png"
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true

defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
    image: "/img/twitter-card.png"

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

feed:
  categories:
    - release

sass:
  style: compressed

exclude:
- .gitignore
- .jekyll-cache
- CNAME
- icomoon-selection.json
- readme.md
